Gibberlings3/EET

- EET/other/cpmvars/eet_cpmvars.tpa
HOUSG3.DLG state 5 in vanilla BG1 is state 0 in BGEE & EET. Adding variable for special handling of interjections on that dialog state.
> Adding dialog state variable for housg3state5

- EET/tbl/compatibility.tbl
~~I'll probably update this with checks if necessary, but hopefully such won't be needed.~~
As of 2022-11-05 EE Fixpack generate warnings on EET, but the result works. I'll migrate the required change to silence these warnings (because the result would mean that EET would explicitly require a Fixpacked SoD).
> Add EE Fixpack compatibility.

- EET/lib/bg2_BCS.tph
https://www.gibberlings3.net/forums/topic/35904-a-script-block-in-baldurbcs-meant-for-the-bg2-portion-can-execute-in-bg1/
> Fix players with rep dipped in BG1 bribing CWs.

- EET/EET.tp2
- EET/compile/d/cleanBG1.d
https://www.gibberlings3.net/forums/topic/34382-shar-teel-and-dorn-bug-out-when-she-challenges-him-to-a-fight/
> Fix Dorn vs. Shar-Teel conflict.

- EET/EET.tp2
- EET/lib/bg1_BCS.tph
- EET/lib/bg1_CRE.tph
- EET/lib/pcu_dict.tph
- EET/lib/prep_SPL.tph
DRGRBRHT.SPL is referred in the SoD assets both as fullcaps and mixed-caps DrGrBrHt in the BCS scripts. In the previous PR, I attempted to resolve this via a single PCU entry and then doing the other steps manually, but that led to some changes being attempted to be installed twice.
This PR drops all the manual steps introduced in the prior PR in favor of duplicating the PCU entry to catch both spelling variations.
> Remove manual steps in favor of PCU duplicate.

- EET/lib/bg1_BCS.tph
Fixes the Shadow Thieves ambush that marks the transition from SoD to BG2.
Party members are immune to the weapon effects of the attackers when Story Mode is active, which causes the event to continue indefinitely without coming to a conclusion.
> Fix SoD-to-BG2 transition when Story Mode is active

- EET/lib/bg1_BCS.tph
This PR fixes an incomplete variable substitution and a missing script action in the regular expression for Imoen's XP adjustment script.
> Fix Imoen's XP adjustment

- EET/lib/bg1_BCS.tph
- EET/lib/bg1_CRE.tph
- Fixes fade-from-black after the Ambush cinematic
- Fixes a creature allegiance to prevent _Auto-Pause: Enemy Sighted_ from triggering during the transition cutscene
> Improve Ambush scripting at SoD ending

- EET/lib/prep_ITM.tph
BG2:EE version of AX1H06.ITM has no unique name and is bugged:
It creates a duplicate on every ranged hit.
> Don't delete BG1:EE version of AX1H06.ITM (Rhyte's Last Arrow +2)

- EET/EET.tp2
Movies with language-specific soundtracks can make use of [movie soundtrack overrides](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/mvesnd.htm) (as it is done with the ToB endgame cinematics).
With this feature enabled it is no longer needed to manually combine audio and video via `ffmpeg`. Removal of the `ffmpeg` binaries reduces mod package size by about 90 MB.
> Use movie soundtrack override feature for movies with voiced audio

- EET/lib/prep_WAV.tph
In German version of BG2:EE these files are corrupt.
> Don't delete WENCH0*.WAV in German

- EET/lib/macros.tph
An error I introduced during adding the logging at one point.
Sorry, I was only looking at BG1 NPCs in my last check, while I should've looked at the SoD NPCs as well.
Follwup of #112.
> Fix duplication of 9-clicks on nonjoinables.

- EET/tbl/compatibility.tbl
Hi, can you add BGEETEXTPACKEETNAMES mod to the compatibility list as it was discussed in #84, please?
This mod is a BG1EE Russian translation (based on original BGEETEXTPACK)  with mainly compatible names for BG2EE Russian translation. 
The long story is: It happened to be that BG1EE and BG2EE official Russian translations were made by two different people and they didn't have the common list how to translate names. So, it is a difference in eg Gorion Russian translation for BG1EE and BG2EE and many other names. Later, the Russian community tried to fix this issue using different means, and this mod is one of them. Russian community already used this mod for the last couple of years for EET installations, however I had to have a branch of EET with this mod in the list (and other ones …
> Add Russian translation with compatible EET names

- EET/lib/prep_BAM.tph
In BG2:EE these files have ugly black backgrounds.
Files are used in MISC52.ITM and MISC54.ITM.
> Don't delete CMISC52.BAM and CMISC54.BAM

- EET/lib/shortcut_windows.tph
This fix correctly handles user names that consist of multiple words. (Fixes #114)
Note:
User names with non-ASCII characters may still cause issues (like #76) as that would require individually tailored codepage changes based on the present character set.
> Make Windows desktop shortcut creation more robust

- EET/lib/bg1_GUI.tph
- EET/lib/bg2_GUI.tph
- Introduces a modified fire spark vfx to the default EET GUI.
- Restores the original fire spark vfx in "EET_gui"*.
<em>*) The vfx was originally disabled in "EET_gui". @K4thos Let me know if there was a good reason for this, and I will undo the changes for "EET_gui".</em>
> Restore fire spark UI effects on start screen when SoD campaign is selected

- EET/EET.tp2
- EET/lib/macros.tph
User directory is retrieved by external batch script to preserve the correct character encoding.
Fixes #76
> [Windows] Fix installation errors when user name contains non-ASCII characters

- EET/lib/prep_WAV.tph
In German version of BG2:EE some files are corrupt.
Some are already handled in PR #100 but not all.
<br>
<details>
<summary>This is a list of all corrupt German *.WAV files in BG2:EE</summary>
- 2YAGA23.WAV
- BODHIX15.WAV
- BODHIX17.WAV
- CELOGA04.WAV
- CHANT01.WAV
- CHANT01B.WAV
- CHANT02.WAV
- CHANT03.WAV
- CHANT04.WAV
- CHANT05.WAV
- CHANT06.WAV
- CHANT07.WAV
- CHANT220.WAV
- DEMSON20.WAV
- GDWARF01.WAV
- GDWARF02.WAV
- GDWARF03.WAV
- GDWARF04.WAV
- GENFG01.WAV
- GGFEM01.WAV
- GGFEM02.WAV
- GGFEM03.WAV
- GGFEM04.WAV
- GGFEM05.WAV
- GGMAL01.WAV
- GGMAL02.WAV
- GGMAL03.WAV
- GGMAL04.WAV
- GNFEM01.WAV
- GNFEM02.WAV
- GNFEM03.WAV
- GNFEM04.WAV
- GNMAL01.WAV
- GNMAL02.WAV
- GNMAL03.WAV
- GNMAL201.WAV
- GNMAL202.WAV
- GNMAL203.WAV
- GNOME01.WAV
- GNOME02.WAV
- GNOME03.WAV
- GNOME04.WAV
- …
> Don't delete specific German *.WAV files

- EET/EET.tp2
BG2 creature animation for Centeol (the fat spider lady) is not fully compatible and results in a missing death animation and permanently blocked personal space even after death.
This commit assigns a copy of the animation to Centeol with a fixed animation attribute.
> Creature animation fix for Centeol creature

- EET/compile/d/cleanBG1.d
Because of scripting differences between BGEE and BG2EE Tersus always hands out 6 leather armor in EET. If party size is smaller then armor of invalid targets pile up in the protagonist's inventory.
> Fix Tersus handing out leather armor to the party
